<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class FoodSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('foods')->insert([
            ['name' => 'Phở bò', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Phở gà', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bún bò Huế', 'id_type' => 1, 'image' => 'default/food9.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bún riêu', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bún mắm', 'id_type' => 1, 'image' => 'default/food9.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hủ tiếu', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mì Quảng', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gỏi cuốn', 'id_type' => 1, 'image' => 'default/food5.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh xèo', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh cuốn', 'id_type' => 1, 'image' => 'default/food5.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh bèo', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cơm tấm', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gà kho gừng', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 1, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cá kho tộ', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gà nướng mật ong', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cá hấp xì dầu', 'id_type' => 1, 'image' => 'default/food5.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mực chiên giòn', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tôm rim', 'id_type' => 1, 'image' => 'default/food4.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gà luộc', 'id_type' => 1, 'image' => 'default/food5.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Thịt kho trứng', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sườn xào chua ngọt', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Canh chua cá', 'id_type' => 1, 'image' => 'default/food5.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Canh bí đỏ', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Canh cải thịt bằm', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rau muống xào tỏi', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cơm chiên dương châu', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cơm gà Hải Nam', 'id_type' => 1, 'image' => 'default/food8.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lẩu thái', 'id_type' => 1, 'image' => 'default/food4.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lẩu cá', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Lẩu nấm chay', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh mì thịt', 'id_type' => 1, 'image' => 'default/food8.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh mì chay', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh tráng trộn', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Chè ba màu', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Chè bắp', 'id_type' => 1, 'image' => 'default/food3.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh flan', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Rau câu dừa', 'id_type' => 1, 'image' => 'default/food4.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Pizza hải sản', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Spaghetti', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Hamburger', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sushi', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Sashimi', 'id_type' => 1, 'image' => 'default/food4.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tempura', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gà rán KFC', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Tokbokki', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Kimchi', 'id_type' => 1, 'image' => 'default/food7.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Cơm chiên trứng', 'id_type' => 1, 'image' => 'default/food10.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Mì xào bò', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh canh cua', 'id_type' => 1, 'image' => 'default/food2.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bánh đúc nóng', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Bún thịt nướng', 'id_type' => 1, 'image' => 'default/food1.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gỏi bò', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
            ['name' => 'Gỏi xoài', 'id_type' => 1, 'image' => 'default/food6.png', 'bestSeller' => 0, 'cost' => 20000, 'detail' => 'Chè ba màu ngọt mát, đậm chất truyền thống.', 'status' => 1, 'created_at' => Carbon::now(), 'updated_at' => Carbon::now(),],
        ]);
    }
}
