services:
  - type: web
    name: laravel-app
    env: docker
    repo: https://github.com/ten-cua-cau/ten-repo.git
    plan: free
    branch: main
    buildFilter:
      paths:
        - Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: <host của MySQL>
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: <tên database>
      - key: DB_USERNAME
        value: <username>
      - key: DB_PASSWORD
        value: <password>
